### ISSUE TITLE
GC% = 0

### ISSUE THREAD

**Issue by alerubio** [oXis/gtool#2]
Hi, I am getting the next output using both examples:

 python ~/installs/bin/gtool.py -sg ~/tools/gtool-master/*.fasta 
SeqName: A
        Contig: 3
        Size: 924
        GC%: 0.0
SeqName: B
        Contig: 3
        Size: 1680
        GC%: 0.0
Any Idea?
Thanks

**Comment by oXis** [comment]
This is probably because your default `python` interpreter is for python 2.7. The script only works for python 3.

> oxis@soyah:[\~/workspace/python/gtool]✔
$ python gtool.py -sg *.fasta
SeqName: A
	Contig: 3
	Size: 924
	GC%: 0.0
SeqName: B
	Contig: 3
	Size: 1680
	GC%: 0.0
oxis@soyah:[\~/workspace/python/gtool]✔
$ python3 gtool.py -sg *.fasta
SeqName: A
	Contig: 3
	Size: 924
	GC%: 48.16
SeqName: B
	Contig: 3
	Size: 1680
	GC%: 45.71

This is because when you do a division of two `int` in python 2 the result is also an `int` whereas in python 3 it's a `float`.

>oxis@soyah:[\~]✔
$ python -c "print 2/3"
0
oxis@soyah:[\~]✔
$ python3 -c "print(2/3)"
0.6666666666666666

**Comment by alerubio** [comment]
Ok, thanks a lot. Now it works with python3
~/tools/python3/python gtool.py -sg A.fasta 
SeqName: A
        Contig: 3
        Size: 924
        GC%: 48.16
Bests
